version: '3.1'

services:
  mongo-docker:
    build: .
    # image: registry.gitlab.com/idgst/springboot-mongo-demo:latest
    restart: always
    container_name: mongo-docker-api
    ports:
      - 8082:8082
    working_dir: /app
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo-docker # Container name
    environment:
      - MONGO_INITDB_DATABASE=mongo-docker
      - MONGO_INITDB_ROOT_USERNAME=sysadmin
      - MONGO_INITDB_ROOT_PASSWORD=sysadmin
    volumes:
      - ./conf/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    #  - ./mongo-volume:/data/db
    ports:  # for demo/debug purpose only
          - 27017:27017
    restart: always