server:
  port: 8082

spring:
  application:
    name: ${MICROSERVICE_NAME:mongo-docker}
    namespace: ${CLOUD_NAMESPACE:unknown}
    cloud_namespace: ${CLOUD_NAMESPACE:unknown}

mongo:
  host: ${MONGO_HOST:mongo}
  port: ${MONGO_PORT:27017}
  dbName: ${MONGO_DB_NAME:mongo-docker}
  user: ${MONGO_USER:microservice_admin}
  password: ${MONGO_PASSWORD:microservice_admin}